# Generated by Django 3.1.7 on 2021-03-07 14:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('created_date', models.DateField(default=django.utils.timezone.now)),
                ('month', models.CharField(max_length=7, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('colors', models.CharField(max_length=20)),
                ('events', models.CharField(max_length=500)),
            ],
        ),
    ]
